In [1]:
import numpy as np

hello = 'Hello, world.'
print(hello)

Hello, world.


In [2]:
# one-dimensional array
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
# two-dimensional array
arr2 = np.array([[1,2], [3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [6]:
arr3 = np.array([1,2,3,4,5,6], ndmin=3)
print(arr3)

arr_float = np.array(arr3, dtype=float)
print(arr_float)

[[[1 2 3 4 5 6]]]
[[[1. 2. 3. 4. 5. 6.]]]


In [7]:
arr_bool = np.array([0,1,0,1], dtype=bool)
print(arr_bool)

[False  True False  True]


In [10]:
# get the array dimensions
print(arr3)
print(arr3.shape)

[[[1 2 3 4 5 6]]]
(1, 1, 6)


In [14]:
# resize an array using the .shape attribute
arr4 = np.array(arr2)
print(arr4)
print(arr4.shape)

arr4.shape = (4,1)
print(arr4)
print(arr4.shape)

[[1 2]
 [3 4]]
(2, 2)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [16]:
arr5 = arr2.reshape(4,1)
print(arr5)

[[1]
 [2]
 [3]
 [4]]


In [18]:
a = np.arange(5,30,2)
print(a)
print(a[:5])
print(a[2:5])
print(a[7:])

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 5  7  9 11 13]
[ 9 11 13]
[19 21 23 25 27 29]


In [19]:
print(a[::-1])

[29 27 25 23 21 19 17 15 13 11  9  7  5]


In [22]:
b = np.array([[1,2,3,4,5], [2,4,6,8,10],
[3,6,9,12,15], [5,10,15,20,25], [6,12,18,24,30]])
print(b, '\n')
print(b[:1], '\n') 
print(b[1:], '\n') 
print(b[::2], '\n') 
print(b[:1, :2])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]] 

[[1 2 3 4 5]] 

[[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]] 

[[ 1  2  3  4  5]
 [ 3  6  9 12 15]
 [ 6 12 18 24 30]] 

[[1 2]]


In [27]:
k = np.array([[1,2,3,4], [2,4,6,8],
[3,6,9,12]])

#print(k)

ksub = k[:3, :2]
#print(k, '\n')
#print(ksub)

ksub[1,0] = 100
print(ksub)
print(k)

[[  1   2]
 [100   4]
 [  3   6]]
[[  1   2   3   4]
 [100   4   6   8]
 [  3   6   9  12]]


In [28]:
m = np.array([9,18,27,36])
n = np.array([10,20,30,40])
o = np.array([7,14,21,28])

print(m,'\n', n, '\n', o)
print(np.concatenate([m,n]))
print(np.concatenate([m,n,o]))

[ 9 18 27 36] 
 [10 20 30 40] 
 [ 7 14 21 28]
[ 9 18 27 36 10 20 30 40]
[ 9 18 27 36 10 20 30 40  7 14 21 28]


In [30]:
print(np.vstack([m,n,o]))
print(np.hstack([m,n,o]))

[[ 9 18 27 36]
 [10 20 30 40]
 [ 7 14 21 28]]
[ 9 18 27 36 10 20 30 40  7 14 21 28]


In [33]:
r = np.arange(8)
print("r =", r)
print("r + 10 =", r + 10)
print("r / 2 =", r / 2)

r = [0 1 2 3 4 5 6 7]
r + 10 = [10 11 12 13 14 15 16 17]
r / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [40]:
s = np.arange(100)

def div_by_2(array):
    v = np.empty(len(array))
    for i in range(len(array)):
        v[i] = i /2
    return v

r2 = div_by_2(r)
#print(r2)

%timeit s2_numpy = s / 2
print(len(s2_numpy))

%timeit s2_loop = div_by_2(s)
print(len(s2_loop))

3.38 µs ± 88.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
100
16.8 µs ± 257 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
100


In [43]:
X = np.random.random(1000)
print(np.sum(X))

x_range = (X.min(), X.max())
print(x_range)

493.32642136290724
(0.0006054494749520023, 0.9987192314201836)


In [47]:
Y = np.random.random((3,4))
print(Y, '\n')

print(Y.sum(axis=0), '\n')
print(Y.sum(axis=1))

[[0.80145258 0.7741406  0.52584705 0.50158972]
 [0.97868938 0.75852347 0.65467488 0.55814459]
 [0.0596622  0.8848943  0.07191196 0.78174846]] 

[1.83980416 2.41755837 1.25243389 1.84148277] 

[2.60302993 2.95003233 1.79821692]


In [52]:
Z = np.random.randint(1,10,100)
print(Z)

print("mean =", np.mean(Z))
print("variance =", np.var(Z))
print("standard deviation =", np.std(Z))
print("median =", np.median(Z))

[6 9 3 9 8 3 9 8 5 6 3 2 9 9 4 1 5 4 5 8 3 1 3 6 8 3 8 8 6 9 4 8 2 3 4 1 9
 5 9 9 9 6 5 4 9 5 7 4 1 2 2 4 9 2 6 7 2 9 7 6 4 6 5 3 9 9 6 3 3 4 9 6 3 1
 5 6 1 8 7 3 8 1 1 7 6 6 5 7 6 2 6 5 7 4 1 9 2 1 9 4]
mean = 5.29
variance = 6.945899999999999
standard deviation = 2.635507541252728
median = 5.0
